PREFIX fam:   <http://www.ifi.uio.no/IN3060/family#> 
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX sim:   <http://www.ifi.uio.no/IN3060/simpsons#> 
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf:  <http://xmlns.com/foaf/0.1/>

#Query: Find everyone who has a mother or a father and list both the person
#and the mother or father. Order by mother/father. Use the result variable
#name ?person, ?parent


1 SELECT ?person ?parent
2 WHERE {
3    { ?person fam:hasMother ?parent }
4 UNION
5    { ?person fam:hasFather ?parent }
6  } ORDER BY ?parent